[theme]

# Primary accent for interactive elements
primaryColor = '#FF4B28'

# Background color for the main content area
backgroundColor = '#000000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#383837'

# Color used for almost all text
textColor = '#FFFFFF'


# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[global]
#false
showWarningOnDirectExecution = true

[client]
# "none"
showErrorDetails = "full"


#removes navigation
#showSidebarNavigation = false